In [1]:
!conda install numpy

Solving environment: ...working... done

# All requested packages already installed.



In [2]:
import numpy as np

### Array

In [5]:
arr1 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

print(arr1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [6]:
np.array(0)

array(0)

In [8]:
arr1(0)

TypeError: 'numpy.ndarray' object is not callable

In [9]:
arr1 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

print(arr1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [10]:
print(arr1[0])
print(arr1[-1])

[1 2 3 4]
[ 9 10 11 12]


In [11]:
list1 = [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

print(list1)

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]


In [12]:
print(list1[0][0])

1


In [15]:
print(arr1[0,2])
print(arr1[0])
print(arr1[:,2])

3
[1 2 3 4]
[ 3  7 11]


In [16]:
arr1.dtype

dtype('int32')

In [20]:
arr2 = np.array([[.2, .4], [.6, .8],[1, 1.2], [1.4, 1.6]])

print(arr2)

[[0.2 0.4]
 [0.6 0.8]
 [1.  1.2]
 [1.4 1.6]]


In [21]:
arr2.dtype

dtype('float64')

In [25]:
arr3 = np.array([
    [
        [1,2,3],
        [11,22,33]
    ],
    [
        [4,5,6],
        [44,55,66]
    ]
])

print(arr3)

[[[ 1  2  3]
  [11 22 33]]

 [[ 4  5  6]
  [44 55 66]]]


In [26]:
# shape of array
print("shape of arr1", arr1.shape)
print("shape of arr2", arr2.shape)
print("shape of arr3", arr3.shape)

# dimension
print("dimension of arr1", arr1.ndim)
print("dimension of arr2", arr2.ndim)
print("dimension of arr3", arr3.ndim)

shape of arr1 (3, 4)
shape of arr2 (4, 2)
shape of arr3 (2, 2, 3)
dimension of arr1 2
dimension of arr2 2
dimension of arr3 3


In [29]:
# array zeros
arr_zeros_1 = np.zeros(10)
arr_zeros_2 = np.zeros([10,5])
arr_zeros_3 = np.zeros([10,5,3])

print(arr_zeros_1, arr_zeros_1.shape)
print("--")
print(arr_zeros_2, arr_zeros_2.shape)
print("--")
print(arr_zeros_3, arr_zeros_3.shape)

# array ones is the same just change zero to one

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] (10,)
--
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]] (10, 5)
--
[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]] (10, 5, 3)


In [32]:
arr_empty = np.empty([4, 2])
print(arr_empty)

# random numbers

[[0.2 0.4]
 [0.6 0.8]
 [1.  1.2]
 [1.4 1.6]]


In [34]:
arr_one = np.arange(0, 50, .2)

print(arr_one)

[ 0.   0.2  0.4  0.6  0.8  1.   1.2  1.4  1.6  1.8  2.   2.2  2.4  2.6
  2.8  3.   3.2  3.4  3.6  3.8  4.   4.2  4.4  4.6  4.8  5.   5.2  5.4
  5.6  5.8  6.   6.2  6.4  6.6  6.8  7.   7.2  7.4  7.6  7.8  8.   8.2
  8.4  8.6  8.8  9.   9.2  9.4  9.6  9.8 10.  10.2 10.4 10.6 10.8 11.
 11.2 11.4 11.6 11.8 12.  12.2 12.4 12.6 12.8 13.  13.2 13.4 13.6 13.8
 14.  14.2 14.4 14.6 14.8 15.  15.2 15.4 15.6 15.8 16.  16.2 16.4 16.6
 16.8 17.  17.2 17.4 17.6 17.8 18.  18.2 18.4 18.6 18.8 19.  19.2 19.4
 19.6 19.8 20.  20.2 20.4 20.6 20.8 21.  21.2 21.4 21.6 21.8 22.  22.2
 22.4 22.6 22.8 23.  23.2 23.4 23.6 23.8 24.  24.2 24.4 24.6 24.8 25.
 25.2 25.4 25.6 25.8 26.  26.2 26.4 26.6 26.8 27.  27.2 27.4 27.6 27.8
 28.  28.2 28.4 28.6 28.8 29.  29.2 29.4 29.6 29.8 30.  30.2 30.4 30.6
 30.8 31.  31.2 31.4 31.6 31.8 32.  32.2 32.4 32.6 32.8 33.  33.2 33.4
 33.6 33.8 34.  34.2 34.4 34.6 34.8 35.  35.2 35.4 35.6 35.8 36.  36.2
 36.4 36.6 36.8 37.  37.2 37.4 37.6 37.8 38.  38.2 38.4 38.6 38.8 39.
 39.2 39.

In [36]:
np.append(arr_one, 50)

array([ 0. ,  0.2,  0.4,  0.6,  0.8,  1. ,  1.2,  1.4,  1.6,  1.8,  2. ,
        2.2,  2.4,  2.6,  2.8,  3. ,  3.2,  3.4,  3.6,  3.8,  4. ,  4.2,
        4.4,  4.6,  4.8,  5. ,  5.2,  5.4,  5.6,  5.8,  6. ,  6.2,  6.4,
        6.6,  6.8,  7. ,  7.2,  7.4,  7.6,  7.8,  8. ,  8.2,  8.4,  8.6,
        8.8,  9. ,  9.2,  9.4,  9.6,  9.8, 10. , 10.2, 10.4, 10.6, 10.8,
       11. , 11.2, 11.4, 11.6, 11.8, 12. , 12.2, 12.4, 12.6, 12.8, 13. ,
       13.2, 13.4, 13.6, 13.8, 14. , 14.2, 14.4, 14.6, 14.8, 15. , 15.2,
       15.4, 15.6, 15.8, 16. , 16.2, 16.4, 16.6, 16.8, 17. , 17.2, 17.4,
       17.6, 17.8, 18. , 18.2, 18.4, 18.6, 18.8, 19. , 19.2, 19.4, 19.6,
       19.8, 20. , 20.2, 20.4, 20.6, 20.8, 21. , 21.2, 21.4, 21.6, 21.8,
       22. , 22.2, 22.4, 22.6, 22.8, 23. , 23.2, 23.4, 23.6, 23.8, 24. ,
       24.2, 24.4, 24.6, 24.8, 25. , 25.2, 25.4, 25.6, 25.8, 26. , 26.2,
       26.4, 26.6, 26.8, 27. , 27.2, 27.4, 27.6, 27.8, 28. , 28.2, 28.4,
       28.6, 28.8, 29. , 29.2, 29.4, 29.6, 29.8, 30

In [46]:
np.append(arr_one, [51], axis=0)

array([ 0. ,  0.2,  0.4,  0.6,  0.8,  1. ,  1.2,  1.4,  1.6,  1.8,  2. ,
        2.2,  2.4,  2.6,  2.8,  3. ,  3.2,  3.4,  3.6,  3.8,  4. ,  4.2,
        4.4,  4.6,  4.8,  5. ,  5.2,  5.4,  5.6,  5.8,  6. ,  6.2,  6.4,
        6.6,  6.8,  7. ,  7.2,  7.4,  7.6,  7.8,  8. ,  8.2,  8.4,  8.6,
        8.8,  9. ,  9.2,  9.4,  9.6,  9.8, 10. , 10.2, 10.4, 10.6, 10.8,
       11. , 11.2, 11.4, 11.6, 11.8, 12. , 12.2, 12.4, 12.6, 12.8, 13. ,
       13.2, 13.4, 13.6, 13.8, 14. , 14.2, 14.4, 14.6, 14.8, 15. , 15.2,
       15.4, 15.6, 15.8, 16. , 16.2, 16.4, 16.6, 16.8, 17. , 17.2, 17.4,
       17.6, 17.8, 18. , 18.2, 18.4, 18.6, 18.8, 19. , 19.2, 19.4, 19.6,
       19.8, 20. , 20.2, 20.4, 20.6, 20.8, 21. , 21.2, 21.4, 21.6, 21.8,
       22. , 22.2, 22.4, 22.6, 22.8, 23. , 23.2, 23.4, 23.6, 23.8, 24. ,
       24.2, 24.4, 24.6, 24.8, 25. , 25.2, 25.4, 25.6, 25.8, 26. , 26.2,
       26.4, 26.6, 26.8, 27. , 27.2, 27.4, 27.6, 27.8, 28. , 28.2, 28.4,
       28.6, 28.8, 29. , 29.2, 29.4, 29.6, 29.8, 30

In [54]:
np.append(arr1, [[10], [11], [12]], axis=1)

array([[ 1,  2,  3,  4, 10],
       [ 5,  6,  7,  8, 11],
       [ 9, 10, 11, 12, 12]])

In [55]:
print(arr1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [56]:
arr_sort = np.array([9, 3, 5, 1, 4, 2, 8])

np.sort(arr_sort)

array([1, 2, 3, 4, 5, 8, 9])

In [58]:
a = np.arange(1,10,.5)

print(a, a.shape, a.size, a.ndim)

[1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5 9.  9.5] (18,) 18 1


In [65]:
b = a.reshape(3,3,2)

print(b)

[[[1.  1.5]
  [2.  2.5]
  [3.  3.5]]

 [[4.  4.5]
  [5.  5.5]
  [6.  6.5]]

 [[7.  7.5]
  [8.  8.5]
  [9.  9.5]]]


In [67]:
print(arr1)
arr1.shape

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


(3, 4)

In [68]:
c = arr1[(arr1 > 2) & (arr1 % 2 ==0)]

print(c)

[ 4  6  8 10 12]


In [69]:
arr1x = arr1 * 19

print(arr1x)

[[ 19  38  57  76]
 [ 95 114 133 152]
 [171 190 209 228]]


In [73]:
print(np.concatenate((arr1, arr1x)))
print(np.concatenate((arr1, arr1x), axis=1))

arr2x = np.concatenate((arr1, arr1x))

[[  1   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]
 [ 19  38  57  76]
 [ 95 114 133 152]
 [171 190 209 228]]
[[  1   2   3   4  19  38  57  76]
 [  5   6   7   8  95 114 133 152]
 [  9  10  11  12 171 190 209 228]]


In [75]:
print(np.split(arr2x, 2))

[array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]]), array([[ 19,  38,  57,  76],
       [ 95, 114, 133, 152],
       [171, 190, 209, 228]])]


In [77]:
np.multiply(arr1, arr1x)

array([[  19,   76,  171,  304],
       [ 475,  684,  931, 1216],
       [1539, 1900, 2299, 2736]])

In [78]:
F

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 4)