In [1]:
egg = 0

def buy_egg():
    egg += 12
    
buy_egg()

UnboundLocalError: local variable 'egg' referenced before assignment

In [2]:
def count_uppercase(string):
    num_upper = 0
    for char in string:
        if not char.isupper():
            continue
        num_upper += 1
    return num_upper

In [3]:
count_uppercase("Welcome to Rocking Rackets")

3

In [4]:
def count_uppercase_2(string):
    num_upper = 0
    for char in string:
        if char.isupper():
            num_upper += 1
    return num_upper

In [5]:
count_uppercase_2("Welcome to Rocking Rackets")

3

# Numpy

In [1]:
import numpy as np

In [5]:
arr1 = np.arange(0, 1, .05)

print(arr1)

[0.   0.05 0.1  0.15 0.2  0.25 0.3  0.35 0.4  0.45 0.5  0.55 0.6  0.65
 0.7  0.75 0.8  0.85 0.9  0.95]


In [6]:
arr2 = arr1.reshape(10, 2)

print(arr2)

[[0.   0.05]
 [0.1  0.15]
 [0.2  0.25]
 [0.3  0.35]
 [0.4  0.45]
 [0.5  0.55]
 [0.6  0.65]
 [0.7  0.75]
 [0.8  0.85]
 [0.9  0.95]]


In [8]:
arr3 = arr2 * 2     # or arr2.dot(2)

print(arr3)

[[0.  0.1]
 [0.2 0.3]
 [0.4 0.5]
 [0.6 0.7]
 [0.8 0.9]
 [1.  1.1]
 [1.2 1.3]
 [1.4 1.5]
 [1.6 1.7]
 [1.8 1.9]]


In [12]:
arr4 = arr2 * arr3 # not this

arr4 = np.matmul(arr2, arr3.T) # correct

print(arr4, arr4.shape)

[[0.005 0.015 0.025 0.035 0.045 0.055 0.065 0.075 0.085 0.095]
 [0.015 0.065 0.115 0.165 0.215 0.265 0.315 0.365 0.415 0.465]
 [0.025 0.115 0.205 0.295 0.385 0.475 0.565 0.655 0.745 0.835]
 [0.035 0.165 0.295 0.425 0.555 0.685 0.815 0.945 1.075 1.205]
 [0.045 0.215 0.385 0.555 0.725 0.895 1.065 1.235 1.405 1.575]
 [0.055 0.265 0.475 0.685 0.895 1.105 1.315 1.525 1.735 1.945]
 [0.065 0.315 0.565 0.815 1.065 1.315 1.565 1.815 2.065 2.315]
 [0.075 0.365 0.655 0.945 1.235 1.525 1.815 2.105 2.395 2.685]
 [0.085 0.415 0.745 1.075 1.405 1.735 2.065 2.395 2.725 3.055]
 [0.095 0.465 0.835 1.205 1.575 1.945 2.315 2.685 3.055 3.425]] (10, 10)


In [18]:
arr4_mean = arr4.mean(axis=0)
print(arr4_mean)
arr4_median = np.median(arr4,axis=0)
print(arr4_median)
print(arr4.std(axis=0), arr4.var(axis=0))

[0.05 0.24 0.43 0.62 0.81 1.   1.19 1.38 1.57 1.76]
[0.05 0.24 0.43 0.62 0.81 1.   1.19 1.38 1.57 1.76]
[0.02872281 0.14361407 0.25850532 0.37339657 0.48828782 0.60317908
 0.71807033 0.83296158 0.94785284 1.06274409] [8.250000e-04 2.062500e-02 6.682500e-02 1.394250e-01 2.384250e-01
 3.638250e-01 5.156250e-01 6.938250e-01 8.984250e-01 1.129425e+00]
